source 'https://rubygems.org'
gem 'rails', '~> 5.2.0'
gem 'pg', '~> 1.1'
gem 'puma', '~> 3.11'
gem 'sass-rails', '~> 5.0'
gem 'webpacker', '~> 4.0'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'rubocop', require: false